fix cost tensor device
pfnet-research/pfhedge pull request #577
Opened 2022-05-02 02:22 UTC by masanorihirano

fix #576

2022-05-09 04:05 UTC, imos approved these changes

2023-03-07 08:43 UTC, imos requested changes

2023-03-07 08:43 UTC, imos commented on pfhedge/_utils/bisect.py
> +        torch.as_tensor(upper, device=price.device),
dtypeも普通は揃えたい気がするので、その時はこっちの方がシンプル

```suggestion
        torch.as_tensor(lower).to(price),
        torch.as_tensor(upper).to(price),
```

2023-03-07 08:43 UTC, imos commented on pfhedge/nn/functional.py
> +        c = torch.tensor(cost, device=spot.device).unsqueeze(0).unsqueeze(-1)
```suggestion
        c = torch.tensor(cost, dtype=spot.dtype, device=spot.device).unsqueeze(0).unsqueeze(-1)
```

2023-03-07 08:43 UTC, imos commented on pfhedge/_utils/bisect.py
> +        upper (Tensor or float): Upper bound of binary search. (If cuda is used, cuda Tensor is necessaary.)
usedってどのレベルで判定される想定ですかね？「CUDAが存在するマシンなら必ず」なのか「pfhedge上で使っていたら必ず」なのか「この関数で使うなら必ず」なのかが読みにくいです。

関数レベルであれば

upper ... Use the same type and device as target uses.

みたいなのでももしかしたら良いかもしれません。

あとコードを見る限りは自動的に変換されているように見えるので実際はこの制約はありますか？

2023-03-07 08:50 UTC, masanorihirano commented on pfhedge/nn/functional.py
> +        c = torch.tensor(cost, device=spot.device).unsqueeze(0).unsqueeze(-1)
こっちも.to(spot)にした方がいい気がしたので，後続コミット出します．

2023-03-07 09:04 UTC, masanorihirano commented on pfhedge/_utils/bisect.py
> +        upper (Tensor or float): Upper bound of binary search. (If cuda is used, cuda Tensor is necessaary.)
「fnの計算において，cuda Tensorとの間で計算が行われる場合には」というのが正確な定義で，fnが任意関数であるために，定義が結構面倒です．たとえば，fn内で適切にgpuへの転送が行われていれば，この条件は不要になります．
ただし，一般に，バイナリサーチのコードで，fn内にgpuへのキャスト処理を要求するのは計算速度の低下を引き起こしますから，現実的ではないでしょう．その場合，この，lowerとupperがgpuに転送されていることがbetterということになります．

コードを見る限り，自動的に変換されているのは，floatやtorch.Tensor以外の型がupper/lowerに入った場合に，Tensorに変える処理だけです．
一般的なユースケースとして，upper/lowerには，floatなどを入れますから，そうなると，Tensorにキャストしても，fnがcuda Tensorを要求する操作である場合には，エラーが起きてしまうわけです．

そのため，この制約はかなり説明が難しく，正直，cuda cpu間の演算エラーが出るなら，cuda Tensorにしてください，というレベルの意味合いになってしまいます．

If cuda is used,がかなり漠然としすぎているのは事実なので，よいとこ，If cuda tensor is required for the input of fn,とするくらいだと思います．

2023-03-07 09:06 UTC, masanorihirano commented on pfhedge/_utils/bisect.py
> +        upper (Tensor or float): Upper bound of binary search. (If cuda is used, cuda Tensor is necessaary.)
後続コミットを作成

2023-03-07 09:11 UTC, imos commented on pfhedge/_utils/bisect.py
> +        upper (Tensor or float): Upper bound of binary search. (If cuda is used, cuda Tensor is necessaary.)
これってtargetと同じ型・デバイスにはできませんか？こっちはfloatではないので。

2023-03-07 09:14 UTC, imos requested changes

2023-03-07 09:14 UTC, imos commented on pfhedge/_utils/bisect.py
> +                                 (If cuda Tensor is required for the input of fn, cuda Tensor is necessaary.)
```suggestion
        lower (Tensor or float): Lower bound of binary search.
                                 This must be a CUDA Tensor if fn expects to input a CUDA Tensor.
        upper (Tensor or float): Upper bound of binary search.
                                 This must be a CUDA Tensor if fn expects to input a CUDA Tensor.
```

2023-03-07 09:15 UTC, imos commented on pfhedge/_utils/bisect.py
> +                                 (If cuda Tensor is required for the input of fn, cuda Tensor is necessaary.)
↑でコメントを書きましたが、 as_tensor した後に to で型を target に揃えればこれは不要になると思うので、検討してみてもらえると。targetと型を揃えるのが変であればコメントで書くので良いと思います。

2023-03-07 09:18 UTC, masanorihirano commented on pfhedge/_utils/bisect.py
> +        upper (Tensor or float): Upper bound of binary search. (If cuda is used, cuda Tensor is necessaary.)
fnの実装次第では，targetとupper/lowerのcpu/cudaの状況は違う可能性もあるので，無理にcastしにくいかも...このケースをNGにするかどうかの議論になります．何が一番良いのか難しいです

2023-03-07 09:20 UTC, masanorihirano commented on pfhedge/_utils/bisect.py
> +        upper (Tensor or float): Upper bound of binary search. (If cuda is used, cuda Tensor is necessaary.)
fnに制約を付けるか，lower/upperに制約を付けるかのどちらにするかの議論ですね．(私は後者の方がbetterだと思っています．)

2023-03-07 09:23 UTC, imos approved these changes
了解です。そういうことであれば良いと思います。自分が他でつけたsuggestを反映させるかはおまかせします。

2023-03-13 23:28 UTC, merged