rBergomi
pfnet-research/pfhedge pull request #583
Opened 2022-06-14 07:02 UTC by masanorihirano

added RoughBergomiStock and generate_rough_bergomi

2022-06-14 07:03 UTC, masanorihirano commented
#448

2022-06-14 07:19 UTC, masanorihirano commented
lint and formatting fails are caused by version problems.
I suppose that the black update should be done in master (or release) branch

2023-03-28 09:46 UTC, imos requested changes
式までしっかり追いかけられているわけではないんですが、外形的に問題ないと思うので良さそうです。超理想的には生成も含めて元実装と同じような出力をすることをテストできると嬉しいですが、一旦notebookと値が近いというのはわかるので良いと思います。

2023-03-28 09:46 UTC, imos commented on pfhedge/stochastic/rough_bergomi.py
> +    dW2 *= dW2.new_tensor(dt).sqrt()
このケースは使いまわしはなさそうではあるので安全ではあるがレポジトリ全体として in-place は極力避けた方が良いと思います。

```suggestion
    dW2 = dW2 * math.sqrt(dt)
```

2023-04-04 01:24 UTC, masanorihirano commented
originalの実装よりも，どうやらこの実装の方が，ボラティリティスマイルの収束精度が高く(たぶん，計算誤差が少ないことによる)，そのため，testの結果の数値の比較をoriginalから取るのではなく，あくまで出力チェックしていただけでした．そのため，originalの実装で，試行数を増やした結果の数値との比較を取ることにしました．(ただし，それでも1%誤差範囲が必要)

2023-04-04 02:04 UTC, imos approved these changes

2023-04-04 02:04 UTC, imos commented on pfhedge/stochastic/rough_bergomi.py
> +    _Y2 = _GXi_convolve[:, torch.arange(-1, -1 - n_steps, -1)]
```suggestion
    _Y2 = _GXi_convolve[:, -n_steps:].flip(1)
```

2023-04-04 02:28 UTC, imos commented
/test

2023-04-04 05:17 UTC, imos commented
/test

2023-04-04 05:33 UTC, merged