Merton Jump-diffusion Model
pfnet-research/pfhedge pull request #585
Opened 2022-07-19 01:15 UTC by masanorihirano

2023-03-28 10:21 UTC, imos requested changes

2023-04-04 01:35 UTC, masanorihirano commented on pfhedge/stochastic/merton_jump.py
> +    jump = n_jumps * jump_size
https://www.codearmo.com/python-tutorial/merton-jump-diffusion-model-python#:~:text=np.random.normal(m%2Cv%2C%20size%3Dsize)
ここの実装では，
```
np.random.normal(m,v, size=size)
```
になっているので，別の出典をあたります．(伊藤の定理とかが噛んでいるところで，結構怪しい．．．)

2023-04-04 01:40 UTC, masanorihirano commented on pfhedge/stochastic/merton_jump.py
> +    jump = n_jumps * jump_size
https://www.imes.boj.or.jp/research/papers/japanese/kk22-b1-3.pdf
式(3)に従えば，指摘が正しそうですし，上記Webが正しくなさそうなのは理論的にもそうだと思うので，修正します．

2023-04-04 02:27 UTC, masanorihirano commented on pfhedge/stochastic/merton_jump.py
> +    jump = n_jumps * jump_size
456effb6e272923c59b50b2cceddb65c33e4abad で修正しました．

2023-04-04 02:33 UTC, masanorihirano commented on pfhedge/stochastic/merton_jump.py
> +    drift = (
https://github.com/pfnet-research/pfhedge/pull/585/files#diff-7fe0e33faf13f750741b31634d4ee1f802976643e27be507e2e53d85bad291d2R11-R46
ここでテストしているものではないですか？ >> @imos

2023-04-04 02:36 UTC, masanorihirano commented on pfhedge/stochastic/merton_jump.py
> +    drift = (
↑はjump幅0 or jump回数0の場合に，mu=0であれば，平均的に元の価格に収束することを確認しています．

2023-04-04 02:44 UTC, masanorihirano commented on pfhedge/stochastic/merton_jump.py
> +    drift = (
伊藤の公式を適用した形で実装しているので，もしかしたら直感に反するかもしれません．
Brownian motionのケースの展開 (https://en.wikipedia.org/wiki/It%C3%B4%27s_lemma#Geometric_Brownian_motion) を見るとしっくりくるかもしれませんが，Brownian motionのほうの実装では，伊藤の公式を適用せずに差分形式で計算しているので，伊藤の公式を適用しない形式での実装は検討のよりがあるかもしれません．(ただし，連続から離散にしたときの近似誤差が大きくなることが想像される．)

2023-04-18 01:41 UTC, imos requested changes
マージの影響でdiffがすごく大きくなっているように見えるんですが、これって修正難しいですか？

2023-04-18 01:41 UTC, imos commented on pfhedge/stochastic/merton_jump.py
> +    drift = (
原著にあたりましたが、どうやらこれが正しい定式化っぽいのでOKです。気になっていたのは `jump_per_year * (jump_mean + jump_std ** 2 / 2)` の部分で、ジャンプが発生していないときにもドリフトが発生するという話ですね。
（自分が似たモデルを設計するならjump側の計算式をいじると思うんですが。）

2023-04-18 01:46 UTC, masanorihirano commented
> マージの影響でdiffがすごく大きくなっているように見えるんですが、これって修正難しいですか？

diff小さくしました．大変失礼いたしました． >> @imos

2023-04-18 02:17 UTC, imos approved these changes

2023-04-18 02:17 UTC, imos commented on pfhedge/instruments/primary/merton_jump.py
> +            from a standard normal distribution.
```suggestion
        mu (float, default=0.0): The drift parameter :math:`\mu`.
        sigma (float, default=0.2): The volatility parameter :math:`\sigma`.
        jump_per_year (float, default=1.0): The average number of jumps per year.
        jump_mean (float, default=0.0): The mean of jumnp sizes.
        jump_std (float, default=0.3): The standard deviation of jump sizes.
        cost (float, default=0.0): The transaction cost rate.
        dt (float, default=1/250): The time step interval.
        dtype (torch.device, optional): Desired device of returned tensor.
            Default: If None, uses a global default
            (see :func:`torch.set_default_tensor_type()`).
        device (torch.device, optional): Desired device of returned tensor.
            Default: if None, uses the current device for the default tensor type
            (see :func:`torch.set_default_tensor_type()`).
            ``device`` will be the CPU for CPU tensor types and
            the current CUDA device for CUDA tensor types.
        engine (callable, default=torch.randn): The desired generator of random numbers
            from a standard normal distribution.
            A function call ``engine(size, dtype=None, device=None)``
            should return a tensor filled with random numbers
            from a standard normal distribution.
```

2023-04-18 02:17 UTC, imos commented on pfhedge/instruments/primary/merton_jump.py
> +          The shape is :math:`(N, T)`.
```suggestion
        - spot (:class:`torch.Tensor`): The spot price of the instrument.
          This attribute is set by the method :meth:`simulate()`.
          The shape is :math:`(N, T)` where
          :math:`N` is the number of simulated paths and
          :math:`T` is the number of time steps.
        - variance (:class:`torch.Tensor`): The variance of the instrument.
          Note that this is different from the realized variance of the spot price.
          This attribute is set by the method :meth:`simulate()`.
          The shape is :math:`(N, T)`.
```

2023-04-18 02:17 UTC, imos commented on pfhedge/stochastic/merton_jump.py
> +        jump_std (float, default=0.02): The deviation of jump sizes.
```suggestion
        jump_per_year (float, default=68.2): The average number of jumps per year.
        jump_mean (float, default=0.0): The mean of jump sizes.
        jump_std (float, default=0.02): The standard deviation of jump sizes.
```

2023-04-18 02:17 UTC, imos commented on pfhedge/stochastic/merton_jump.py
> +        dt (float, default=1/250): The intervals of the time steps.
```suggestion
        dt (float, default=1/250): The time step interval.
```

2023-04-18 06:10 UTC, merged