Quadratic cvar
pfnet-research/pfhedge pull request #588
Opened 2022-08-23 05:09 UTC by masanorihirano

2023-04-11 02:26 UTC, imos requested changes

2023-04-11 02:26 UTC, imos commented on pfhedge/nn/functional.py
> +            return fn.relu(-_omega - input).mean()
dim == 0の扱いが怪しい。おそらく整理するとこんな感じで書ける。unsqueezeするのではなく、本当に不要になったときにmeanなりで次元を潰した方が取り回しやすいはず。

```suggestion
    output_target = torch.as_tensor(1 / (2 * lam))
    base = input.mean(dim=dim, keepdim=True)
    input = input - base

    def fn_target(omega: Tensor) -> Tensor:
        return fn.relu(-omega - input).mean(dim=dim)
```

2023-04-11 02:26 UTC, imos commented on pfhedge/nn/functional.py
> +    """  # NOQA
dim is None は別処理した方が確実かつ読みやすい

```suggestion
    """  # NOQA
    if dim is None:
        return quadratic_cvar(input.flatten(), lam, 0)
```

2023-04-11 02:26 UTC, imos commented on pfhedge/nn/functional.py
> +        return omega + lam * fn.relu(-omega - input).square().mean() - base
dim is None のケースがなくなればシンプルに書けるはず。

```suggestion
    return omega + lam * fn.relu(-omega.unsqueeze(dim=dim) - input).square().mean(dim=dim) - base
```

2023-04-11 02:38 UTC, imos commented
/test

2023-04-17 23:24 UTC, masanorihirano commented
dim=Noneとdim=0の挙動は異なるはずだったので，追加コミットで修正します．
 - dim=None : 次元のないスカラーを返す
 - dim=0 : 0次元目でつぶす

2023-04-18 02:38 UTC, imos approved these changes

2023-04-18 02:38 UTC, imos commented on pfhedge/nn/functional.py
> +        dim (int, optional): The dimension to sort along.
```suggestion
        input (torch.Tensor): The input tensor.
        lam (float): The :math:`lambda` parameter, representing the weight given to the tail losses.
        dim (int, optional): The dimension to sort along. If None, the tensor is flattened.
```

2023-04-18 02:38 UTC, imos commented on pfhedge/nn/functional.py
> +        torch.Tensor
```suggestion
        torch.Tensor: The Quadratic CVaR of the input tensor.
```

2023-04-18 02:38 UTC, imos commented on pfhedge/nn/functional.py
> +    output_target = torch.as_tensor(1 / (2 * lam))
意味が分かれるので分ける

```suggestion
    if dim is None:
        return quadratic_cvar(input.flatten(), lam, 0)

    output_target = torch.as_tensor(1 / (2 * lam))
```

2023-04-18 03:05 UTC, merged