Autorelease by github action
pfnet-research/pfhedge pull request #615
Opened 2023-03-28 09:15 UTC by masanorihirano

automate release procedures.

including
 - pypi upload
 - automatical version tagging
 - automatical release page generation

2023-03-28 09:19 UTC, masanorihirano commented
See successful example: https://github.com/masanorihirano/pfhedge/releases/tag/0.21.0a5

2023-03-29 00:43 UTC, imos requested changes

2023-03-29 00:43 UTC, imos commented on .github/workflows/release.yml
> +    - name: release
```suggestion
    - name: Release to PyPI
```

2023-03-29 00:52 UTC, imos commented
リリースでmainを更新する方式は二度手間になりがちなのと、今の方式だとblameもできないので変えたいです。このPRを先に入れるかは判断を任せます。

- developブランチは削除し、mainブランチに一本化する
- リリースは手動workflow https://docs.github.com/ja/actions/managing-workflow-runs/manually-running-a-workflow を使ってリリース名を引数にとり、手動リリースするような形式の方が望ましいです
    - 強いていうならば今のmainの位置づけとしてlatestというタグを作っても良いですが、用途はあまりないと思います
    - 手動にするとトリガーも容易になります

あとGitHubのリリースを作成したあとにPyPIパッケージが作られる方が挙動としては安心できると思います。

2023-04-04 03:50 UTC, masanorihirano commented
まず，Blameを取れない件については，マージの際にSquashの設定を入れていることが主たる原因ではないでしょうか？その場合，release/* のブランチのマージだけSquashしないとかできれば，問題は解決できる気がします．(理解が違ったらすみません)

> developブランチは削除し、mainブランチに一本化する

これは，問題ないと思います．mainブランチに一本化しても，release/*のブランチを切れば，今やろうとしていることはできますし，PRベースのリリースを避けるとしたら，ますますその通りだと思います．

> リリースは手動workflow https://docs.github.com/ja/actions/managing-workflow-runs/manually-running-a-workflow を使ってリリース名を引数にとり、手動リリースするような形式の方が望ましいです

これについては，原状では悩ましいです．確かに，手動リリースできた方がうれしいのですが，リリースに当たって，version bumpがマストです．version bumpするとなると，現状のmainをプロテクトしている(していますよね？)状況では，github actionからでもcommitが直接できないため，PRを作成し，手動マージするという人手が必要になります．
そのため，
 1. 手動でversion bumpのgithub actionをtriggerする
 2. 自動で生成されるPull Requestをマージする
 3. その後，手動でreleaseのgithub actionを実行する

という順番になり，かなり煩雑なのと，1/2の手順を忘れて3を実施すると，エラーします．残念ながらPyPIに冪等性がない(=同じバージョンでの上書きリリースができない)ために，安易にgithub actionをtriggerできてしまう状況はあまりよろしくないです．

原状の私の設計は以下になっています：
 1. release/*というブランチを作成する
 2. 自動的にVersion bumpのRPがrelease/*宛てに作成されるのでマージする
 3. release/* -> mainという PRを手動で作成し，コメント欄にリリースノートを書く
 4. 3のPRをマージすると，自動的にリリースが行われる(PyPI + releaseページ w/ リリースノート)

これであれば，releaseブランチを起点に，作業漏れが起きないと思っています．

> 強いていうならば今のmainの位置づけとしてlatestというタグを作っても良いですが、用途はあまりないと思います

不要だと思います．

> 手動にするとトリガーも容易になります

上記も踏まえたうえで相談かと思います．(手動トリガーの仕方はもちろん，理解しているつもりです．)

2023-04-04 05:24 UTC, imos requested changes

2023-04-04 05:24 UTC, imos commented on .github/workflows/release.yml
> +name: Release
ブランチの関係性、リリースの流れについてコメント書いておいてもらえますか？
できればrunの中身が見えてなくても理解できるようにしてほしいです（つまり動作が理解できるようにコメントでもnameの形でも良いので書き込んでおいて欲しいです）。

2023-04-04 06:46 UTC, masanorihirano commented
すべて修正しましたので，ご確認ください． > @imos 

また，議論に従い，どこかのタイミングでdevを廃止したいと思っていますが，運用テストも兼ねて，このPRをマージしたら，devをmainにマージし，その後，他のPRのマージ先をmainに変えたいと思います．

2023-04-04 07:41 UTC, imos requested changes

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +name: Release
```suggestion
# `release` workflow configuration
#
# This workflow is triggered when a release branch is merged into the main
# branch. It automates the process of creating a package and releasing it to
# GitHub and PyPI.
#
# Workflow steps:
# 0. A release branch named release/[TAG] is merged into main via a pull
#    request.
# 1. `tagging` job runs:
#     - A branch named [TAG] is created
# 2. `release` job runs:
#     - Create a PyPI package
#     - Create a release on GitHub
#     - Release the package on PyPI
# 3. `delete-branch` job runs:
#     - Delete the release branch .
name: Release
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
可能であれば複数行に分けたほうが見やすい

```suggestion
    if:
      github.event.pull_request.merged == true
      && startsWith(github.event.pull_request.head.ref, 'release/')
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +         #memo: extract version name from branch name (release/x.y.x -> x.y.z) and register it to steps.get_version.outputs.TAG
```suggestion
       - name: Determine the tag name based on the branch name
         id: get_version
         run: |
           echo "TAG=$(echo $BRANCH | cut -d / -f 2)" >> $GITHUB_OUTPUT
         env:
           BRANCH: ${{ github.event.pull_request.head.ref }}
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +         #memo: echo release version for debugging
```suggestion
       - name: Print the tag name for debugging
         run: echo "${{ steps.get_version.outputs.TAG }}"
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +         #memo: push tag to the head of the branch as github action bot user
```suggestion
       - name: Create a corresponding tag branch
         run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
           git fetch origin ${{ github.event.pull_request.head.ref }}
           git checkout main
           git tag -a `echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///'` -m " "
           git push origin `echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///'`
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +      #memo: only one version should be set. This matrix is used to reduce the maintenance cost to change version
```suggestion
      # NOTE: Only one version is selected in order to reduce the cost to change versions.
      matrix:
        python-version: ['3.9']
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +      #memo: extract version name from branch name (release/x.y.x -> x.y.z) and register it to steps.get_version.outputs.TAG
```suggestion
    - name: Determine the tag name based on the branch name
      id: get_version
      run: |
        echo "TAG=$(echo $BRANCH | cut -d / -f 2)" >> $GITHUB_OUTPUT
      env:
        BRANCH: ${{ github.event.pull_request.head.ref }}
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +    - name: Create build
```suggestion
    - name: Build the package
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +    - name: Create release
```suggestion
    - name: Push a release to GitHub
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +    - name: Upload tar.gz
```suggestion
    - name: Attach an archive of source files to the release
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +    - name: Upload whl
```suggestion
    - name: Attach a Python wheel to the release
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +    - name: Upload checksum
```suggestion
    - name: Attach the checksum of the files to the release
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +    - name: Release to PyPI
```suggestion
    - name: Release the version to PyPI
```

2023-04-04 07:41 UTC, imos commented on .github/workflows/release.yml
> +    - name: Delete branch
```suggestion
    - name: Delete the release branch
```

2023-04-04 08:07 UTC, masanorihirano commented on .github/workflows/release.yml
> +    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
別コミットで修正

2023-04-04 08:10 UTC, masanorihirano commented on .github/workflows/release.yml
> +      #memo: only one version should be set. This matrix is used to reduce the maintenance cost to change version
https://github.com/pfnet-research/pfhedge/pull/615/commits/f8287af4b04b5048ebe4b9afa9b998453053f3fb

2023-04-04 08:10 UTC, masanorihirano commented on .github/workflows/release.yml
> +    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
https://github.com/pfnet-research/pfhedge/pull/615/commits/f8287af4b04b5048ebe4b9afa9b998453053f3fb

2023-04-04 08:22 UTC, imos approved these changes

2023-04-04 08:22 UTC, imos commented on .github/workflows/release.yml
> +#     - Delete the release branch .
```suggestion
#     - Delete the release branch
```

2023-04-04 08:28 UTC, merged