[WIP] 202303 description updates
pfnet-research/pfhedge pull request #616
Opened 2023-03-28 09:23 UTC by masanorihirano

2023-04-04 09:29 UTC, imos requested changes

2023-04-04 09:29 UTC, imos commented on .github/CONTRIBUTING.md
> +3. Create pull request from "release/*" to "main" and write release note on the body of the pull request.
ここ日本語で説明してもらえますか？生成されるPRと作るPRはそれぞれどういう役割？最初のPRはrelease/が何にマージされるPRですか？

2023-04-11 01:09 UTC, imos requested changes

2023-04-11 01:09 UTC, imos commented on .github/CONTRIBUTING.md
> +3. Create pull request from "release/*" to "main" and write release note on the body of the pull request.
```suggestion
1. Create a release branch named with the prefix "release/".
2. A pull request to update the version information in the release branch is automatically generated. Then, review and merge the pull request.
3. Create a pull request from "release/*" to "main", and write release notes in the description of the pull request.
```

2023-04-11 01:09 UTC, imos commented on .github/CONTRIBUTING.md
> +Note: dev/develop branch is no longer used for development. Please make pull request directly into main branch.
```suggestion
4. When the pull request is merged into the main branch, a PyPI release and a release page will be automatically configured.
    - Please do not remove the release branch by yourself. Github Actions will automatically delete the release branch once the release process is done.

NOTE: dev/develop branch is no longer used for development. Please make a pull request directly into main branch.
```

2023-04-11 01:12 UTC, masanorihirano commented on .github/CONTRIBUTING.md
> +Note: dev/develop branch is no longer used for development. Please make pull request directly into main branch.
a release page -> a github release pageに後で変更します

2023-04-11 01:39 UTC, imos approved these changes

2023-04-11 01:39 UTC, imos commented on .github/CONTRIBUTING.md
> +## Release Procedures For Maintainers
```suggestion
## Release Process for Maintainers
```

2023-04-11 01:58 UTC, merged